[project]
name = "wii_music_editor"
version = "2.0.0-dev.4"
description = "The ultimate Wii Music modding tool"
authors = [
    { name = "Benjamin Halko" },
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.9,<3.13"
dependencies = [
    "importlib_metadata",
    "mido",
    "packaging",
    "pretty-midi",
    "psutil",
    "pypresence",
    "pyside6",
    "requests",
    "setuptools"
]

[project.scripts]
wii-music-editor = "wii_music_editor:main"

[project.urls]
homepage = "https://github.com/BenjaminHalko/WiiMusicEditorPlus"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
wii_music_editor = "wii_music_editor"

[tool.cibuildwheel]
skip = ["*-musllinux*", "pp*", "*-win32"]
repair-wheel-command = ""

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"
manylinux-aarch64-image = "manylinux2014"

[semantic_release]
assets = []
commit_message = "{version}\n\nAutomatically generated by python-semantic-release"
commit_parser = "angular"
logging_use_named_masks = false
major_on_zero = true
tag_format = "v{version}"

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]

[tool.semantic_release.branches.main]
match = "main"
prerelease = false

[tool.semantic_release.branches.dev]
match = "dev"
prerelease = true
prerelease_token = "dev"

[semantic_release.changelog.environment]
block_start_string = "{%"
block_end_string = "%}"
variable_start_string = "{{"
variable_end_string = "}}"
comment_start_string = "{#"
comment_end_string = "#}"
trim_blocks = false
lstrip_blocks = false
newline_sequence = "\n"
keep_trailing_newline = false
extensions = []
autoescape = true

[semantic_release.commit_parser_options]
allowed_tags = ["build", "chore", "ci", "docs", "feat", "fix", "perf", "style", "refactor", "test"]
minor_tags = ["feat"]
patch_tags = ["fix", "perf"]
default_bump_level = 0
